-keep class com.wisesmartchurch.system.model.** { *; }
-keep class com.wisesmartchurch.system.server.** { *; }
-keepclassmembers class * extends fi.iki.elonen.NanoWSD$WebSocket { *; }
-keep class fi.iki.elonen.** { *; }
-keep class org.json.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
